name: Lean
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: leanprover/lean-action@50fcf42d2e460296f1a34b402e990d1b24f8b596 # v1
        with:
          auto-config: false
          build: false
          test: false
          lint: false
          use-github-cache: false
          use-mathlib-cache: false
      - run: lake exe cache get
      - run: lake build AlgebraicGroupModel AGMTest
